### PR TITLE
[663] scrolling sector graph

### LINKED ISSUE #663: [Bug]: Company Sectors Legend not Scrolling
### Environment

stagine

### Urgency

Medium (should be updated soon)

### Steps to Reproduce

1. Go to sector graphs
2. Click on a industry with lots of companies

### Expected Behavior

Legend should scroll not expand

### Actual Behavior

is expands to full length

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by kaylawoodbury**
### ✨ What’s Changed?

- fix legend scroll on sector graphs
- fix %bar on scope analysis cards
- fix % format on key insights section
- fix favicon
- reimplement PR template

### 📸 Screenshots (if applicable)

Screenshot 2025-04-30 at 16 14 18

Screenshot 2025-04-30 at 16 14 31

### 📋 Checklist

- [x] PR title starts with [#issue-number]; if no issue is applicable use: [fix], [feat], [prod], or [copy]
- [x] I've verified the change runs locally
- [x] I've set the labels, issue, and milestone for the PR
- [ ] [OPTIONAL] I've created sub-tasks or follow-up issues as needed (check if NA)

### 🛠 Related Issue

Closes #663 #656

### CODE REVIEW

File: src/components/companies/sectors/charts/PieLegend.tsx [hunk 1]
```diff
@@ -60,7 +60,7 @@ const PieLegend: React.FC<PieLegendProps> = ({
             : screenSize.isTablet
               ? "grid-cols-1"
               : "grid-cols-2"
-        } gap-2 max-h-[${screenSize.isMobile ? "200" : "500"}px] overflow-y-auto w-full pr-2 ${
+        } gap-2 max-h-[${screenSize.isMobile ? "300" : "500"}px] overflow-y-auto w-full pr-2 ${
```
Comment (elvbom) [inline src/components/companies/sectors/charts/PieLegend.tsx:63]: Easier to use 

```suggestion
        } gap-2 max-h-300px md:max-h-500px overflow-y-auto w-full pr-2 ${
```

?

**Review by elvbom — COMMENTED** [review]
Just looked at the code. Im having issues with running API locally that I dont have time to solve before logging off, but it looks good! :)
