### PR TITLE
[728] Add dashed line for estimated emissions

### LINKED ISSUE #728: [Change Request]: Indicate Estimated Emissions
### Background / Why This Change?

On the municipality historical emissions chart, we are not currently indicating when emissions are the reported emissions vs which are our estimated emissions. This gives the incorrect impression for users.

### What Should Be Changed?

- add dashed line for estimated emissions
- in tool tip clarify these are estimated emissions

### Screenshots or Visuals (optional)

Image

### Urgency

High (blocking release or critical for users)

### PR DESCRIPTION
**Pull request by kaylawoodbury**
### ✨ What’s Changed?

Add a dashed line for the estimated/calculated emissions for municipalities, and add text to indicate that in the tool tip also

### 📸 Screenshots (if applicable)

**Before**
Screenshot 2025-05-15 at 10 39 34

**After**
Screenshot 2025-05-15 at 10 41 48

**Before**
Screenshot 2025-05-15 at 11 25 34

**After**
Screenshot 2025-05-15 at 11 25 21

**Before**
Screenshot 2025-05-15 at 11 25 29

**After**
Screenshot 2025-05-15 at 11 25 05

Before
Screenshot 2025-05-15 at 11 31 05

After
Screenshot 2025-05-15 at 11 31 22

### 📋 Checklist

- [x] PR title starts with [#issue-number]; if no issue is applicable use: [fix], [feat], [prod], or [copy]
- [x] I've verified the change runs locally
- [x] I've set the labels, issue, and milestone for the PR
- [x] [OPTIONAL] I've created sub-tasks or follow-up issues as needed (check if NA)

### 🛠 Related Issue

Closes #728

### CODE REVIEW

File: src/components/layout/InfoTooltip.tsx [hunk 1]
```diff
@@ -0,0 +1,27 @@
+import { Info } from "lucide-react";
```
Comment (hallski) [inline src/components/layout/InfoTooltip.tsx:1]: I noticed `lucide-react` also export everything as `<Name>Icon`, which I have been using as I find it clearer what it is, maybe we should align (and possibly see if we make sure code editors only suggest one or the other)?

**Review by hallski — APPROVED** [review]
Added a small comment which is unrelated to this PR but we can have a chat about separately.
