### PR TITLE
[943] Company cards displaying NaN and Infinite

### LINKED ISSUE #943: [Bug]: Displaying NaN on company overview cards
### Environment

Production

### Urgency

Medium (should be updated soon)

### Steps to Reproduce

1. Go to Companies page
2. Scroll down to the bottom for the companies with lowest emissions.
3. See the displayed values on the cards compared to the company details values.

### Expected Behavior

Should be displaying No data if no data is available.

### Actual Behavior

Instead displaying NaN-value.

### Screenshots

Image

### PR DESCRIPTION
**Pull request by CarlWiren90**
### ✨ What’s Changed?

Added checks for 0, NaN and finite to avoid the company cards displaying NaN and -100% when no data is present. 
Now also treating a 0 value on latest reporting period as a No Data-point since it's the same logic we're using to determine NoData on the company details page.

### 📸 Screenshots (if applicable)

Before: 
image

After:
image

### 📋 Checklist

- [x] PR title starts with [#issue-number]; if no issue is applicable use: [fix], [feat], [prod], or [copy]
- [x] I've verified the change runs locally both on mobile and desktop
- [x] I've set the labels, issue, and milestone for the PR
- [ ] [OPTIONAL] I've created sub-tasks or follow-up issues as needed (check if NA)

### 🛠 Related Issue

Closes #943

### CODE REVIEW

**Comment by CarlWiren90** [comment]
I believe this now cover the cases where we were displaying weird numbers and are now correctly displaying No Data when there is none available. Also added the translation for "mdr" and "bn" to be displayed depending on SV/EN. Talked to @elvbom about this yesterday and the conditions inside the JSX is getting abit messy. Might be good to create a util to handle the logic for this and just return the "No Data" if the numbers don't meet the reqs. Perhaps we can merge this and that will be a follow up later on?

@kaylawoodbury @elvbom

File: src/components/companies/list/CompanyCard.tsx [hunk 1]
```diff
@@ -52,14 +52,18 @@ export function CompanyCard({
   const currentEmissions = latestPeriod?.emissions?.calculatedTotalEmissions;
   const previousEmissions = previousPeriod?.emissions?.calculatedTotalEmissions;
   const emissionsChange =
-    previousEmissions != null && currentEmissions != null
+    previousEmissions != null &&
+    currentEmissions != null &&
+    previousEmissions != 0 &&
+    currentEmissions != 0
```
Comment (elvbom) [inline src/components/companies/list/CompanyCard.tsx:58]: This could maybe be divided into two consts with checks for previousEmissions and currentEmissions and then reused in more parts of the code?

**Review by elvbom — COMMENTED** [review]
Good job! Some minor comments :)

**Comment by CarlWiren90** [comment]
Morning!

Separated the checks for previousEmissions and currentEmissions to two different consts as per your suggestion @elvbom. Therefore also removed the null checks inside the jsx. Added translation for "mdr" to toggle from "mdr" to "bn" depending on language. Also deleted commented out code inside the component.

File: src/components/companies/list/CompanyCard.tsx [hunk 2]
```diff
@@ -234,34 +197,40 @@ export function CompanyCard({
...
+                      <AiIcon size="sm" />
+                    </span>
+                  )}
+                </Text>
+              ) : (
+                <Text variant="h6" className="text-grey">
+                  {t("companies.card.noData")}
+                </Text>
+              )}
+            </>
```
Comment (elvbom) [inline src/components/companies/list/CompanyCard.tsx:232]: This could use a slight rewrite - it would need a check for latestPeriodEconomyTurnover.value and the <></> could be removed for example

**Review by elvbom — COMMENTED** [review]
Looking good! One minor comment :)

File: src/components/companies/list/CompanyCard.tsx (hunk 2 above)
Comment (CarlWiren90) [reply src/components/companies/list/CompanyCard.tsx:232]: So as to change line 209 to {latestPeriodEconomyTurnover?.value ? instead?
