### PR TITLE
[FIX] Asorted Fixes: Package-lock, mobile scrolling, type error

### LINKED ISSUE #1070: [Bug]:  Mobile scrolling issue
### Environment

Production

### Urgency

Medium (should be updated soon)

### Steps to Reproduce

1. Go to "Companies"
2. Choose "List", sort by Total Emissions
3. Scroll down. It is not possible to scroll past company "Nederman"
4. Alternatively, sort according to "Change in emissions" – when it gets to the bottom, a company overlaps with partner logos

### Expected Behavior

To be able to scroll down to the bottom of site and see all the companies

### Actual Behavior

When sorted according to "Total emissions": it is not possible to scroll past company "Nederman"
When sorted according to "Change in emissions": when it gets to the bottom, company info overlaps with partner logos

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by kaylawoodbury**
### ✨ What’s Changed?

PR includes a few key fixes: 
- fixes package lock to resume correct merging (CI issues from previous merges)
- fixes a type error on useCompanies hook
- simplified type definitions as a result of the above fix
- fixes error on scrolling company list view on mobile

### 📸 Screenshots (if applicable)

No visual change except fixing of scrolling

### 📋 Checklist

- [x] PR title starts with [#issue-number]; if no issue is applicable use: [fix], [feat], [prod], or [copy]
- [ ] I've verified the change runs locally both on mobile and desktop
- [ ] I've set the labels, issue, and milestone for the PR
- [ ] [OPTIONAL] I've created sub-tasks or follow-up issues as needed (check if NA)

### 🛠 Related Issue

Related to and closes #1070

### CODE REVIEW

File: src/components/companies/list/CompanyCard.tsx [hunk 1]
```diff
@@ -223,13 +230,15 @@ export function CompanyCard({
...
         <LinkCard
-          link={latestPeriod.reportURL ? latestPeriod.reportURL : undefined}
+          link={latestPeriod?.reportURL ? latestPeriod.reportURL : undefined}
           title={t("companies.card.companyReport")}
           description={
             noSustainabilityReport
               ? t("companies.card.missingReport")
               : t("companies.card.reportYear", {
-                  year: new Date(latestPeriod.endDate).getFullYear(),
+                  year: latestPeriod?.endDate
```
Comment (elvbom) [inline src/components/companies/list/CompanyCard.tsx:239]: How come this addition? Im spontanously thinking it might display incorrect year (ie 2025 if there is no year for latestPeriod) but might have gotten that all wrong?

File: src/utils/data/cleaning.ts [hunk 2]
```diff
@@ -8,7 +6,20 @@ function normalizeTotalField<T extends { total?: number | null }>(
...
+ * Why `any` type is used here:
+ * - Two different API endpoints return different structures:
+ *   - List endpoint (/companies/): Simple structure without IDs
+ *   - Detail endpoint (/companies/{wikidataId}): Complex structure with IDs and additional metadata
+ * - The function needs to handle both structures gracefully
+ * - Complex union types would be unwieldy and hard to maintain
+ * - Type safety comes from usage sites, not this utility function
+ * - The function preserves important fields (id, metadata.user, metadata.comment, metadata.source)
+ *   that are used throughout the codebase for AI detection and edit forms
+ */
```
Comment (elvbom) [inline src/utils/data/cleaning.ts:21]: Great clarification! :)
